"""empty message

Revision ID: 2de9fb5d6c99
Revises: f43c729d4f0f
Create Date: 2020-11-17 18:50:08.626696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de9fb5d6c99'
down_revision = 'f43c729d4f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen2', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen2')
    # ### end Alembic commands ###
